In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
escalar = np.array(42)
print(escalar)
print(type(escalar))

42
<class 'numpy.ndarray'>


In [5]:
vector = np.array([2,3,5,5,9,9])
print(vector)
print(type(vector))

[2 3 5 5 9 9]
<class 'numpy.ndarray'>


In [6]:
matrix = np.array([[3,5,7],[11,13,17],[19,23,29]])
print(matrix)
print(type(matrix))

[[ 3  5  7]
 [11 13 17]
 [19 23 29]]
<class 'numpy.ndarray'>
